version: "3"
services:
  server:
    container_name: nisa_ocr
    build:
      context: .
      dockerfile: Dockerfile
    image: nisa_ocr_server
    ports:
        - "3001:3001"
    networks:
      - web
networks:
  web:
