{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webservice.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
  labels:
{{ include "webservice.labels" . | nindent 4 }}
{{- end -}}

